import type { AlchemyElement, CategoryId, ElementId } from './types'

function el(
  id: ElementId,
  category: CategoryId,
  emoji: string,
  en: string,
  pl: string,
  a?: ElementId,
  b?: ElementId,
): AlchemyElement {
  return { id, category, emoji, name: { en, pl }, recipes: a && b ? [[a, b]] : undefined }
}

/**
 * Every element in the game. An element is made by combining two ingredients (order does not
 * matter, and both may be the same element); each element has a main recipe here and may have more
 * in ALTERNATIVE_RECIPES below. The tests guarantee that every element is reachable starting from
 * the four basics and that no two elements share a recipe.
 */
const BASE_ELEMENTS: AlchemyElement[] = [
  // ── Basics ──
  el('water', 'basic', '💧', 'Water', 'Woda'),
  el('fire', 'basic', '🔥', 'Fire', 'Ogień'),
  el('earth', 'basic', '🌍', 'Earth', 'Ziemia'),
  el('air', 'basic', '💨', 'Air', 'Powietrze'),

  // ── Nature ──
  el('mud', 'nature', '🟤', 'Mud', 'Błoto', 'water', 'earth'),
  el('lava', 'nature', '🌋', 'Lava', 'Lawa', 'fire', 'earth'),
  el('dust', 'nature', '🌫️', 'Dust', 'Kurz', 'air', 'earth'),
  el('energy', 'nature', '⚡', 'Energy', 'Energia', 'fire', 'air'),
  el('bubble', 'nature', '🫧', 'Bubble', 'Bąbelek', 'water', 'air'),
  el('wind', 'nature', '🌬️', 'Wind', 'Wiatr', 'air', 'air'),
  el('puddle', 'nature', '🫗', 'Puddle', 'Kałuża', 'rain', 'earth'),
  el('mountain', 'nature', '⛰️', 'Mountain', 'Góra', 'earth', 'earth'),
  el('range', 'nature', '🏔️', 'Mountain range', 'Pasmo górskie', 'mountain', 'mountain'),
  el('volcano', 'nature', '🗻', 'Volcano', 'Wulkan', 'mountain', 'lava'),
  el('hill', 'nature', '🟩', 'Hill', 'Wzgórze', 'earth', 'grass'),
  el('cave', 'nature', '🕳️', 'Cave', 'Jaskinia', 'mountain', 'tool'),
  el('lake', 'nature', '🏞️', 'Lake', 'Jezioro', 'water', 'water'),
  el('river', 'nature', '🛶', 'River', 'Rzeka', 'water', 'mountain'),
  el('waterfall', 'nature', '💦', 'Waterfall', 'Wodospad', 'river', 'stone'),
  el('valley', 'nature', '🌄', 'Valley', 'Dolina', 'mountain', 'river'),
  el('ocean', 'nature', '🌊', 'Ocean', 'Ocean', 'lake', 'lake'),
  el('island', 'nature', '🏝️', 'Island', 'Wyspa', 'ocean', 'earth'),
  el('beach', 'nature', '🏖️', 'Beach', 'Plaża', 'sand', 'ocean'),
  el('desert', 'nature', '🏜️', 'Desert', 'Pustynia', 'sand', 'sun'),
  el('canyon', 'nature', '🪨', 'Canyon', 'Kanion', 'river', 'desert'),
  el('oasis', 'nature', '🏕️', 'Oasis', 'Oaza', 'desert', 'lake'),
  el('swamp', 'nature', '🟢', 'Swamp', 'Bagno', 'mud', 'plant'),
  el('glacier', 'nature', '🧊', 'Glacier', 'Lodowiec', 'ice', 'mountain'),
  el('forest', 'nature', '🌲', 'Forest', 'Las', 'tree', 'tree'),
  el('jungle', 'nature', '🍃', 'Jungle', 'Dżungla', 'forest', 'rain'),
  el('meadow', 'nature', '🌼', 'Meadow', 'Łąka', 'grass', 'flower'),
  el('field', 'nature', '🚜', 'Field', 'Pole', 'earth', 'wheat'),
  el('coral', 'nature', '🪸', 'Coral', 'Koral', 'ocean', 'life'),
  el('shell', 'nature', '🐚', 'Shell', 'Muszla', 'beach', 'life'),
  el('pearl', 'nature', '⚪', 'Pearl', 'Perła', 'shell', 'sand'),
  el('earthquake', 'nature', '📳', 'Earthquake', 'Trzęsienie ziemi', 'earth', 'energy'),
  el('tsunami', 'nature', '🌊', 'Tsunami', 'Tsunami', 'ocean', 'earthquake'),
  el('sunrise', 'nature', '🌅', 'Sunrise', 'Wschód słońca', 'sun', 'earth'),
  el('sunset', 'nature', '🌇', 'Sunset', 'Zachód słońca', 'sun', 'ocean'),
  el('day', 'nature', '🌞', 'Day', 'Dzień', 'sky', 'sun'),
  el('night', 'nature', '🌃', 'Night', 'Noc', 'sky', 'moon'),
  el('time', 'nature', '🕐', 'Time', 'Czas', 'day', 'night'),

  // ── Weather ──
  el('steam', 'weather', '♨️', 'Steam', 'Para', 'water', 'fire'),
  el('cloud', 'weather', '☁️', 'Cloud', 'Chmura', 'steam', 'air'),
  el('rain', 'weather', '🌧️', 'Rain', 'Deszcz', 'cloud', 'water'),
  el('cold', 'weather', '❄️', 'Cold', 'Zimno', 'rain', 'air'),
  el('ice', 'weather', '🧊', 'Ice', 'Lód', 'water', 'cold'),
  el('snow', 'weather', '🌨️', 'Snow', 'Śnieg', 'cloud', 'cold'),
  el('storm', 'weather', '⛈️', 'Storm', 'Burza', 'cloud', 'energy'),
  el('lightning', 'weather', '🌩️', 'Lightning', 'Piorun', 'storm', 'air'),
  el('tornado', 'weather', '🌪️', 'Tornado', 'Tornado', 'storm', 'dust'),
  el('blizzard', 'weather', '🥶', 'Blizzard', 'Zamieć', 'snow', 'storm'),
  el('fog', 'weather', '🌁', 'Fog', 'Mgła', 'cloud', 'earth'),
  el('sky', 'weather', '🌤️', 'Sky', 'Niebo', 'cloud', 'air'),
  el('rainbow', 'weather', '🌈', 'Rainbow', 'Tęcza', 'rain', 'sun'),
  el('aurora', 'weather', '🎇', 'Aurora', 'Zorza polarna', 'sky', 'lightning'),

  // ── Space ──
  el('sun', 'space', '☀️', 'Sun', 'Słońce', 'sky', 'fire'),
  el('moon', 'space', '🌙', 'Moon', 'Księżyc', 'sky', 'stone'),
  el('star', 'space', '⭐', 'Star', 'Gwiazda', 'sky', 'energy'),
  el('eclipse', 'space', '🌑', 'Eclipse', 'Zaćmienie', 'sun', 'moon'),
  el('constellation', 'space', '✨', 'Constellation', 'Gwiazdozbiór', 'sky', 'star'),
  el('meteor', 'space', '🌠', 'Meteor', 'Meteor', 'star', 'air'),
  el('comet', 'space', '☄️', 'Comet', 'Kometa', 'star', 'ice'),
  el('supernova', 'space', '💥', 'Supernova', 'Supernowa', 'star', 'fire'),
  el('blackhole', 'space', '🌀', 'Black hole', 'Czarna dziura', 'star', 'energy'),
  el('planet', 'space', '🪐', 'Planet', 'Planeta', 'star', 'earth'),
  el('mars', 'space', '🔴', 'Mars', 'Mars', 'planet', 'desert'),
  el('galaxy', 'space', '🌌', 'Galaxy', 'Galaktyka', 'star', 'star'),
  el('universe', 'space', '♾️', 'Universe', 'Wszechświat', 'galaxy', 'galaxy'),
  el('alien', 'space', '👽', 'Alien', 'Kosmita', 'planet', 'animal'),
  el('ufo', 'space', '🛸', 'UFO', 'UFO', 'alien', 'metal'),
  el('satellite', 'space', '🛰️', 'Satellite', 'Satelita', 'moon', 'rocket'),
  el('astronaut', 'space', '🧑‍🚀', 'Astronaut', 'Astronauta', 'human', 'rocket'),
  el('telescope', 'space', '🔭', 'Telescope', 'Teleskop', 'glass', 'star'),

  // ── Materials ──
  el('stone', 'materials', '🪨', 'Stone', 'Kamień', 'lava', 'water'),
  el('sand', 'materials', '🟨', 'Sand', 'Piasek', 'stone', 'air'),
  el('glass', 'materials', '🥃', 'Glass', 'Szkło', 'sand', 'fire'),
  el('metal', 'materials', '⚙️', 'Metal', 'Metal', 'stone', 'fire'),
  el('tool', 'materials', '🔨', 'Tool', 'Narzędzie', 'metal', 'stone'),
  el('wall', 'materials', '🧱', 'Wall', 'Mur', 'stone', 'mud'),
  el('wood', 'materials', '🪵', 'Wood', 'Drewno', 'tree', 'tool'),
  el('ash', 'materials', '🩶', 'Ash', 'Popiół', 'campfire', 'air'),
  el('coal', 'materials', '⚫', 'Coal', 'Węgiel', 'wood', 'lava'),
  el('gold', 'materials', '🥇', 'Gold', 'Złoto', 'metal', 'sun'),
  el('diamond', 'materials', '💎', 'Diamond', 'Diament', 'coal', 'mountain'),
  el('paper', 'materials', '📄', 'Paper', 'Papier', 'wood', 'mud'),
  el('cloth', 'materials', '🧵', 'Cloth', 'Tkanina', 'grass', 'tool'),
  el('pyramid', 'materials', '🔺', 'Pyramid', 'Piramida', 'sand', 'stone'),
  el('magnet', 'materials', '🧲', 'Magnet', 'Magnes', 'metal', 'energy'),
  el('campfire', 'materials', '🏕️', 'Campfire', 'Ognisko', 'wood', 'fire'),

  // ── Plants ──
  el('life', 'plants', '🧬', 'Life', 'Życie', 'mud', 'energy'),
  el('plant', 'plants', '🌱', 'Plant', 'Roślina', 'life', 'earth'),
  el('grass', 'plants', '🌿', 'Grass', 'Trawa', 'plant', 'air'),
  el('tree', 'plants', '🌳', 'Tree', 'Drzewo', 'plant', 'rain'),
  el('flower', 'plants', '🌸', 'Flower', 'Kwiat', 'plant', 'sun'),
  el('fruit', 'plants', '🍎', 'Fruit', 'Owoc', 'tree', 'flower'),
  el('wheat', 'plants', '🌾', 'Wheat', 'Pszenica', 'grass', 'sun'),
  el('seed', 'plants', '🌰', 'Seed', 'Nasiono', 'fruit', 'earth'),
  el('nut', 'plants', '🥜', 'Nut', 'Orzech', 'seed', 'tree'),
  el('palm', 'plants', '🌴', 'Palm', 'Palma', 'tree', 'beach'),
  el('coconut', 'plants', '🥥', 'Coconut', 'Kokos', 'palm', 'fruit'),
  el('cactus', 'plants', '🌵', 'Cactus', 'Kaktus', 'plant', 'desert'),
  el('bamboo', 'plants', '🎍', 'Bamboo', 'Bambus', 'grass', 'tree'),
  el('clover', 'plants', '🍀', 'Clover', 'Koniczyna', 'grass', 'rain'),
  el('rose', 'plants', '🌹', 'Rose', 'Róża', 'flower', 'fire'),
  el('sunflower', 'plants', '🌻', 'Sunflower', 'Słonecznik', 'flower', 'sun'),
  el('mushroom', 'plants', '🍄', 'Mushroom', 'Grzyb', 'plant', 'moon'),
  el('garden', 'plants', '🌷', 'Garden', 'Ogród', 'flower', 'human'),

  // ── Animals ──
  el('bird', 'animals', '🐦', 'Bird', 'Ptak', 'life', 'air'),
  el('feather', 'animals', '🪶', 'Feather', 'Pióro', 'bird', 'air'),
  el('egg', 'animals', '🥚', 'Egg', 'Jajko', 'bird', 'life'),
  el('chicken', 'animals', '🐔', 'Chicken', 'Kura', 'egg', 'wheat'),
  el('duck', 'animals', '🦆', 'Duck', 'Kaczka', 'bird', 'lake'),
  el('swan', 'animals', '🦢', 'Swan', 'Łabędź', 'bird', 'river'),
  el('owl', 'animals', '🦉', 'Owl', 'Sowa', 'bird', 'night'),
  el('penguin', 'animals', '🐧', 'Penguin', 'Pingwin', 'bird', 'ice'),
  el('parrot', 'animals', '🦜', 'Parrot', 'Papuga', 'bird', 'jungle'),
  el('fish', 'animals', '🐟', 'Fish', 'Ryba', 'life', 'water'),
  el('whale', 'animals', '🐋', 'Whale', 'Wieloryb', 'fish', 'ocean'),
  el('shark', 'animals', '🦈', 'Shark', 'Rekin', 'fish', 'tool'),
  el('dolphin', 'animals', '🐬', 'Dolphin', 'Delfin', 'fish', 'bubble'),
  el('octopus', 'animals', '🐙', 'Octopus', 'Ośmiornica', 'fish', 'cave'),
  el('crab', 'animals', '🦀', 'Crab', 'Krab', 'animal', 'beach'),
  el('turtle', 'animals', '🐢', 'Turtle', 'Żółw', 'animal', 'shell'),
  el('animal', 'animals', '🐾', 'Animal', 'Zwierzę', 'life', 'grass'),
  el('frog', 'animals', '🐸', 'Frog', 'Żaba', 'swamp', 'animal'),
  el('snake', 'animals', '🐍', 'Snake', 'Wąż', 'animal', 'sand'),
  el('cow', 'animals', '🐄', 'Cow', 'Krowa', 'animal', 'grass'),
  el('pig', 'animals', '🐖', 'Pig', 'Świnia', 'animal', 'mud'),
  el('sheep', 'animals', '🐑', 'Sheep', 'Owca', 'animal', 'cloud'),
  el('goat', 'animals', '🐐', 'Goat', 'Koza', 'animal', 'mountain'),
  el('horse', 'animals', '🐎', 'Horse', 'Koń', 'animal', 'wheat'),
  el('deer', 'animals', '🦌', 'Deer', 'Jeleń', 'animal', 'forest'),
  el('mouse', 'animals', '🐭', 'Mouse', 'Mysz', 'animal', 'house'),
  el('rabbit', 'animals', '🐇', 'Rabbit', 'Królik', 'animal', 'carrot'),
  el('elephant', 'animals', '🐘', 'Elephant', 'Słoń', 'animal', 'tree'),
  el('monkey', 'animals', '🐒', 'Monkey', 'Małpa', 'animal', 'jungle'),
  el('bear', 'animals', '🐻', 'Bear', 'Niedźwiedź', 'animal', 'cave'),
  el('polarbear', 'animals', '🐻‍❄️', 'Polar bear', 'Niedźwiedź polarny', 'bear', 'ice'),
  el('wolf', 'animals', '🐺', 'Wolf', 'Wilk', 'animal', 'moon'),
  el('dog', 'animals', '🐕', 'Dog', 'Pies', 'wolf', 'human'),
  el('cat', 'animals', '🐈', 'Cat', 'Kot', 'animal', 'sun'),
  el('fox', 'animals', '🦊', 'Fox', 'Lis', 'cat', 'forest'),
  el('lion', 'animals', '🦁', 'Lion', 'Lew', 'cat', 'desert'),
  el('tiger', 'animals', '🐅', 'Tiger', 'Tygrys', 'cat', 'jungle'),
  el('bat', 'animals', '🦇', 'Bat', 'Nietoperz', 'animal', 'night'),
  el('dinosaur', 'animals', '🦖', 'Dinosaur', 'Dinozaur', 'animal', 'time'),
  el('insect', 'animals', '🐛', 'Insect', 'Owad', 'life', 'plant'),
  el('butterfly', 'animals', '🦋', 'Butterfly', 'Motyl', 'insect', 'flower'),
  el('bee', 'animals', '🐝', 'Bee', 'Pszczoła', 'insect', 'air'),
  el('ant', 'animals', '🐜', 'Ant', 'Mrówka', 'insect', 'earth'),
  el('spider', 'animals', '🕷️', 'Spider', 'Pająk', 'insect', 'wall'),
  el('snail', 'animals', '🐌', 'Snail', 'Ślimak', 'insect', 'shell'),
  el('worm', 'animals', '🪱', 'Worm', 'Robak', 'life', 'mud'),

  // ── Food ──
  el('flour', 'food', '🥣', 'Flour', 'Mąka', 'wheat', 'stone'),
  el('dough', 'food', '🫓', 'Dough', 'Ciasto', 'flour', 'water'),
  el('bread', 'food', '🍞', 'Bread', 'Chleb', 'dough', 'fire'),
  el('pasta', 'food', '🍝', 'Pasta', 'Makaron', 'dough', 'water'),
  el('pizza', 'food', '🍕', 'Pizza', 'Pizza', 'dough', 'cheese'),
  el('pie', 'food', '🥧', 'Apple pie', 'Szarlotka', 'dough', 'fruit'),
  el('pretzel', 'food', '🥨', 'Pretzel', 'Precel', 'dough', 'salt'),
  el('croissant', 'food', '🥐', 'Croissant', 'Rogalik', 'dough', 'butter'),
  el('cake', 'food', '🍰', 'Cake', 'Tort', 'flour', 'egg'),
  el('cookie', 'food', '🍪', 'Cookie', 'Ciastko', 'flour', 'sugar'),
  el('sugar', 'food', '🍬', 'Sugar', 'Cukier', 'plant', 'stone'),
  el('candy', 'food', '🍭', 'Candy', 'Cukierek', 'sugar', 'sugar'),
  el('chocolate', 'food', '🍫', 'Chocolate', 'Czekolada', 'sugar', 'tree'),
  el('salt', 'food', '🧂', 'Salt', 'Sól', 'ocean', 'fire'),
  el('milk', 'food', '🥛', 'Milk', 'Mleko', 'cow', 'human'),
  el('cheese', 'food', '🧀', 'Cheese', 'Ser', 'milk', 'air'),
  el('butter', 'food', '🧈', 'Butter', 'Masło', 'milk', 'tool'),
  el('icecream', 'food', '🍦', 'Ice cream', 'Lody', 'milk', 'ice'),
  el('omelette', 'food', '🍳', 'Fried eggs', 'Jajecznica', 'egg', 'fire'),
  el('meat', 'food', '🥩', 'Meat', 'Mięso', 'animal', 'fire'),
  el('bacon', 'food', '🥓', 'Bacon', 'Boczek', 'pig', 'fire'),
  el('sausage', 'food', '🍖', 'Sausage', 'Kiełbasa', 'pig', 'tool'),
  el('hotdog', 'food', '🌭', 'Hot dog', 'Hot dog', 'sausage', 'bread'),
  el('sandwich', 'food', '🥪', 'Sandwich', 'Kanapka', 'bread', 'cheese'),
  el('burger', 'food', '🍔', 'Burger', 'Burger', 'bread', 'cow'),
  el('rice', 'food', '🍚', 'Rice', 'Ryż', 'grass', 'water'),
  el('sushi', 'food', '🍣', 'Sushi', 'Sushi', 'rice', 'fish'),
  el('soup', 'food', '🍲', 'Soup', 'Zupa', 'plant', 'water'),
  el('salad', 'food', '🥗', 'Salad', 'Sałatka', 'plant', 'tool'),
  el('potato', 'food', '🥔', 'Potato', 'Ziemniak', 'plant', 'earth'),
  el('fries', 'food', '🍟', 'Fries', 'Frytki', 'potato', 'fire'),
  el('carrot', 'food', '🥕', 'Carrot', 'Marchewka', 'plant', 'sand'),
  el('tomato', 'food', '🍅', 'Tomato', 'Pomidor', 'plant', 'fruit'),
  el('corn', 'food', '🌽', 'Corn', 'Kukurydza', 'plant', 'wheat'),
  el('popcorn', 'food', '🍿', 'Popcorn', 'Popcorn', 'corn', 'fire'),
  el('banana', 'food', '🍌', 'Banana', 'Banan', 'fruit', 'jungle'),
  el('grape', 'food', '🍇', 'Grapes', 'Winogrona', 'fruit', 'sun'),
  el('lemon', 'food', '🍋', 'Lemon', 'Cytryna', 'fruit', 'cold'),
  el('orange', 'food', '🍊', 'Orange', 'Pomarańcza', 'fruit', 'fire'),
  el('strawberry', 'food', '🍓', 'Strawberry', 'Truskawka', 'flower', 'fruit'),
  el('honey', 'food', '🍯', 'Honey', 'Miód', 'bee', 'flower'),
  el('juice', 'food', '🧃', 'Juice', 'Sok', 'fruit', 'water'),
  el('tea', 'food', '🍵', 'Tea', 'Herbata', 'plant', 'steam'),
  el('coffee', 'food', '☕', 'Coffee', 'Kawa', 'seed', 'fire'),
  el('beer', 'food', '🍺', 'Beer', 'Piwo', 'wheat', 'water'),
  el('wine', 'food', '🍷', 'Wine', 'Wino', 'fruit', 'glass'),
  el('champagne', 'food', '🍾', 'Champagne', 'Szampan', 'wine', 'bubble'),
  el('cocktail', 'food', '🍹', 'Cocktail', 'Drink', 'juice', 'wine'),

  // ── People ──
  el('human', 'people', '🧑', 'Human', 'Człowiek', 'animal', 'tool'),
  el('farmer', 'people', '🧑‍🌾', 'Farmer', 'Rolnik', 'human', 'field'),
  el('baker', 'people', '🥖', 'Baker', 'Piekarz', 'human', 'bread'),
  el('chef', 'people', '🧑‍🍳', 'Chef', 'Kucharz', 'human', 'meat'),
  el('doctor', 'people', '🧑‍⚕️', 'Doctor', 'Lekarz', 'human', 'life'),
  el('knight', 'people', '🤺', 'Knight', 'Rycerz', 'human', 'sword'),
  el('king', 'people', '🤴', 'King', 'Król', 'human', 'crown'),
  el('queen', 'people', '👸', 'Queen', 'Królowa', 'human', 'king'),
  el('pirate', 'people', '🏴‍☠️', 'Pirate', 'Pirat', 'human', 'ship'),
  el('snowman', 'people', '⛄', 'Snowman', 'Bałwan', 'snow', 'human'),
  el('santa', 'people', '🎅', 'Santa Claus', 'Mikołaj', 'human', 'snowman'),
  el('heart', 'people', '❤️', 'Heart', 'Serce', 'energy', 'life'),
  el('love', 'people', '💕', 'Love', 'Miłość', 'heart', 'human'),
  el('baby', 'people', '👶', 'Baby', 'Dziecko', 'human', 'love'),
  el('family', 'people', '👪', 'Family', 'Rodzina', 'human', 'baby'),
  el('ghost', 'people', '👻', 'Ghost', 'Duch', 'human', 'night'),
  el('zombie', 'people', '🧟', 'Zombie', 'Zombie', 'human', 'swamp'),
  el('vampire', 'people', '🧛', 'Vampire', 'Wampir', 'human', 'bat'),
  el('ring', 'people', '💍', 'Ring', 'Pierścionek', 'fire', 'gold'),
  el('crown', 'people', '👑', 'Crown', 'Korona', 'gold', 'diamond'),
  el('sword', 'people', '⚔️', 'Sword', 'Miecz', 'fire', 'metal'),
  el('shield', 'people', '🛡️', 'Shield', 'Tarcza', 'metal', 'wall'),

  // ── Places ──
  el('house', 'places', '🏠', 'House', 'Dom', 'wall', 'wood'),
  el('city', 'places', '🏙️', 'City', 'Miasto', 'house', 'house'),
  el('castle', 'places', '🏰', 'Castle', 'Zamek', 'wall', 'human'),
  el('bridge', 'places', '🌉', 'Bridge', 'Most', 'wood', 'water'),
  el('park', 'places', '🛝', 'Park', 'Park', 'city', 'garden'),
  el('shop', 'places', '🏪', 'Shop', 'Sklep', 'house', 'human'),
  el('bank', 'places', '🏦', 'Bank', 'Bank', 'house', 'money'),
  el('school', 'places', '🏫', 'School', 'Szkoła', 'house', 'book'),
  el('library', 'places', '📚', 'Library', 'Biblioteka', 'book', 'book'),
  el('university', 'places', '🎓', 'University', 'Uniwersytet', 'school', 'knowledge'),
  el('hospital', 'places', '🏥', 'Hospital', 'Szpital', 'house', 'doctor'),
  el('church', 'places', '⛪', 'Church', 'Kościół', 'house', 'star'),
  el('stadium', 'places', '🏟️', 'Stadium', 'Stadion', 'ball', 'city'),
  el('door', 'places', '🚪', 'Door', 'Drzwi', 'wood', 'tool'),
  el('window', 'places', '🪟', 'Window', 'Okno', 'glass', 'wall'),
  el('tent', 'places', '⛺', 'Tent', 'Namiot', 'campfire', 'cloth'),

  // ── Transport ──
  el('boat', 'transport', '⛵', 'Boat', 'Łódź', 'wood', 'lake'),
  el('ship', 'transport', '🚢', 'Ship', 'Statek', 'boat', 'metal'),
  el('submarine', 'transport', '🛥️', 'Submarine', 'Łódź podwodna', 'ship', 'water'),
  el('anchor', 'transport', '⚓', 'Anchor', 'Kotwica', 'metal', 'ocean'),
  el('wheel', 'transport', '🛞', 'Wheel', 'Koło', 'wood', 'stone'),
  el('car', 'transport', '🚗', 'Car', 'Samochód', 'wheel', 'metal'),
  el('bus', 'transport', '🚌', 'Bus', 'Autobus', 'car', 'human'),
  el('train', 'transport', '🚆', 'Train', 'Pociąg', 'car', 'car'),
  el('bicycle', 'transport', '🚲', 'Bicycle', 'Rower', 'human', 'wheel'),
  el('motorcycle', 'transport', '🏍️', 'Motorcycle', 'Motocykl', 'bicycle', 'energy'),
  el('plane', 'transport', '✈️', 'Plane', 'Samolot', 'bird', 'metal'),
  el('helicopter', 'transport', '🚁', 'Helicopter', 'Helikopter', 'plane', 'wind'),
  el('rocket', 'transport', '🚀', 'Rocket', 'Rakieta', 'plane', 'fire'),
  el('balloon', 'transport', '🎈', 'Balloon', 'Balon', 'air', 'paper'),
  el('parachute', 'transport', '🪂', 'Parachute', 'Spadochron', 'balloon', 'human'),

  // ── Tech ──
  el('electricity', 'tech', '🔌', 'Electricity', 'Prąd', 'metal', 'lightning'),
  el('battery', 'tech', '🔋', 'Battery', 'Bateria', 'electricity', 'metal'),
  el('lamp', 'tech', '💡', 'Lamp', 'Lampa', 'fire', 'glass'),
  el('candle', 'tech', '🕯️', 'Candle', 'Świeca', 'bee', 'fire'),
  el('computer', 'tech', '💻', 'Computer', 'Komputer', 'electricity', 'knowledge'),
  el('robot', 'tech', '🤖', 'Robot', 'Robot', 'computer', 'metal'),
  el('phone', 'tech', '📱', 'Phone', 'Telefon', 'radio', 'computer'),
  el('internet', 'tech', '🌐', 'Internet', 'Internet', 'computer', 'computer'),
  el('email', 'tech', '📧', 'E-mail', 'E-mail', 'internet', 'paper'),
  el('game', 'tech', '🎮', 'Video game', 'Gra komputerowa', 'computer', 'energy'),
  el('tv', 'tech', '📺', 'Television', 'Telewizor', 'glass', 'electricity'),
  el('radio', 'tech', '📻', 'Radio', 'Radio', 'electricity', 'music'),
  el('microscope', 'tech', '🔬', 'Microscope', 'Mikroskop', 'glass', 'life'),
  el('clock', 'tech', '🕰️', 'Clock', 'Zegar', 'glass', 'metal'),
  el('watch', 'tech', '⌚', 'Watch', 'Zegarek', 'clock', 'human'),
  el('hourglass', 'tech', '⏳', 'Hourglass', 'Klepsydra', 'sand', 'glass'),
  el('compass', 'tech', '🧭', 'Compass', 'Kompas', 'magnet', 'map'),
  el('map', 'tech', '🗺️', 'Map', 'Mapa', 'earth', 'paper'),
  el('calendar', 'tech', '📅', 'Calendar', 'Kalendarz', 'paper', 'time'),
  el('key', 'tech', '🔑', 'Key', 'Klucz', 'metal', 'tool'),
  el('lock', 'tech', '🔒', 'Padlock', 'Kłódka', 'key', 'metal'),
  el('mirror', 'tech', '🪞', 'Mirror', 'Lustro', 'glass', 'water'),
  el('glasses', 'tech', '👓', 'Glasses', 'Okulary', 'glass', 'human'),
  el('camera', 'tech', '📷', 'Camera', 'Aparat', 'glass', 'sun'),
  el('fireworks', 'tech', '🎆', 'Fireworks', 'Fajerwerki', 'energy', 'rocket'),

  // ── Culture ──
  el('book', 'culture', '📖', 'Book', 'Książka', 'paper', 'paper'),
  el('knowledge', 'culture', '🧠', 'Knowledge', 'Wiedza', 'human', 'book'),
  el('music', 'culture', '🎵', 'Music', 'Muzyka', 'human', 'air'),
  el('song', 'culture', '🎶', 'Song', 'Piosenka', 'human', 'music'),
  el('guitar', 'culture', '🎸', 'Guitar', 'Gitara', 'wood', 'music'),
  el('piano', 'culture', '🎹', 'Piano', 'Pianino', 'metal', 'music'),
  el('drum', 'culture', '🥁', 'Drum', 'Bęben', 'animal', 'music'),
  el('dance', 'culture', '💃', 'Dance', 'Taniec', 'energy', 'music'),
  el('party', 'culture', '🎉', 'Party', 'Impreza', 'dance', 'human'),
  el('movie', 'culture', '🎬', 'Movie', 'Film', 'book', 'electricity'),
  el('painting', 'culture', '🖼️', 'Painting', 'Obraz', 'paper', 'rainbow'),
  el('money', 'culture', '💰', 'Money', 'Pieniądze', 'gold', 'paper'),
  el('coin', 'culture', '🪙', 'Coin', 'Moneta', 'gold', 'tool'),
  el('ball', 'culture', '⚽', 'Ball', 'Piłka', 'wheel', 'air'),
  el('trophy', 'culture', '🏆', 'Trophy', 'Puchar', 'gold', 'stadium'),
  el('medal', 'culture', '🏅', 'Medal', 'Medal', 'gold', 'human'),
  el('bed', 'culture', '🛏️', 'Bed', 'Łóżko', 'cloud', 'wood'),
  el('chair', 'culture', '🪑', 'Chair', 'Krzesło', 'human', 'wood'),
  el('umbrella', 'culture', '☂️', 'Umbrella', 'Parasol', 'paper', 'rain'),
  el('shirt', 'culture', '👕', 'Shirt', 'Koszulka', 'cloth', 'human'),
  el('shoe', 'culture', '👟', 'Shoes', 'Buty', 'animal', 'cloth'),
  el('flag', 'culture', '🚩', 'Flag', 'Flaga', 'cloth', 'wood'),
  el('medicine', 'culture', '💊', 'Medicine', 'Lekarstwo', 'plant', 'knowledge'),

  // ── Myth ──
  el('dragon', 'myth', '🐉', 'Dragon', 'Smok', 'bird', 'lava'),
  el('phoenix', 'myth', '🦅', 'Phoenix', 'Feniks', 'bird', 'fire'),
  el('unicorn', 'myth', '🦄', 'Unicorn', 'Jednorożec', 'horse', 'rainbow'),
  el('pegasus', 'myth', '🐴', 'Pegasus', 'Pegaz', 'bird', 'horse'),
  el('centaur', 'myth', '🏇', 'Centaur', 'Centaur', 'human', 'horse'),
  el('mermaid', 'myth', '🧜', 'Mermaid', 'Syrena', 'human', 'fish'),
  el('angel', 'myth', '😇', 'Angel', 'Anioł', 'human', 'bird'),
  el('devil', 'myth', '😈', 'Devil', 'Diabeł', 'fire', 'human'),
  el('elf', 'myth', '🧝', 'Elf', 'Elf', 'human', 'forest'),
  el('troll', 'myth', '🧌', 'Troll', 'Troll', 'human', 'cave'),
  el('magic', 'myth', '🪄', 'Magic', 'Magia', 'energy', 'book'),
  el('wizard', 'myth', '🧙', 'Wizard', 'Czarodziej', 'human', 'magic'),
  el('fairy', 'myth', '🧚', 'Fairy', 'Wróżka', 'flower', 'magic'),
  el('genie', 'myth', '🧞', 'Genie', 'Dżin', 'lamp', 'magic'),
  el('wand', 'myth', '🎩', 'Wand', 'Różdżka', 'magic', 'wood'),
  el('crystalball', 'myth', '🔮', 'Crystal ball', 'Kryształowa kula', 'glass', 'magic'),
  el('potion', 'myth', '🧪', 'Potion', 'Eliksir', 'magic', 'water'),
  el('golem', 'myth', '🗿', 'Golem', 'Golem', 'magic', 'stone'),
]

/**
 * Extra ways to make an element, on top of the main recipe written in BASE_ELEMENTS.
 * A pair of elements always makes exactly one result, so no pair may appear twice anywhere (the tests check this).
 */
const ALTERNATIVE_RECIPES: Partial<Record<ElementId, [ElementId, ElementId][]>> = {
  mud: [['dust', 'water']],
  mountain: [['earth', 'stone']],
  volcano: [['mountain', 'fire']],
  lake: [['rain', 'water']],
  river: [
    ['lake', 'mountain'],
    ['rain', 'mountain'],
  ],
  ocean: [
    ['water', 'lake'],
    ['river', 'river'],
  ],
  island: [
    ['ocean', 'mountain'],
    ['earth', 'lake'],
  ],
  beach: [
    ['sand', 'lake'],
    ['sand', 'water'],
  ],
  desert: [['sand', 'sand']],
  forest: [
    ['plant', 'tree'],
    ['earth', 'tree'],
  ],
  earthquake: [
    ['earth', 'lightning'],
    ['energy', 'mountain'],
  ],
  tsunami: [
    ['ocean', 'storm'],
    ['ocean', 'wind'],
  ],
  day: [['sky', 'sunrise']],
  steam: [
    ['fire', 'ice'],
    ['energy', 'water'],
  ],
  cloud: [['steam', 'wind']],
  rain: [['steam', 'cold']],
  cold: [
    ['cloud', 'wind'],
    ['water', 'wind'],
  ],
  ice: [['rain', 'cold']],
  snow: [['rain', 'ice']],
  storm: [['cloud', 'lightning']],
  tornado: [
    ['wind', 'wind'],
    ['storm', 'wind'],
  ],
  blizzard: [['snow', 'wind']],
  fog: [['steam', 'earth']],
  sky: [['cloud', 'cloud']],
  rainbow: [['rain', 'sky']],
  aurora: [['sky', 'cold']],
  moon: [['planet', 'stone']],
  meteor: [['comet', 'fire']],
  comet: [
    ['cold', 'star'],
    ['ice', 'meteor'],
  ],
  planet: [['star', 'stone']],
  mars: [
    ['fire', 'planet'],
    ['dust', 'planet'],
  ],
  galaxy: [['blackhole', 'star']],
  universe: [['galaxy', 'star']],
  alien: [['human', 'planet']],
  ufo: [
    ['alien', 'plane'],
    ['alien', 'rocket'],
  ],
  satellite: [['rocket', 'star']],
  astronaut: [['human', 'satellite']],
  telescope: [['glass', 'sky']],
  stone: [['fire', 'mud']],
  sand: [['stone', 'wind']],
  glass: [['lava', 'sand']],
  metal: [['lava', 'stone']],
  gold: [
    ['metal', 'star'],
    ['stone', 'sun'],
  ],
  diamond: [['coal', 'lava']],
  paper: [
    ['tree', 'water'],
    ['steam', 'wood'],
  ],
  cloth: [['sheep', 'tool']],
  magnet: [['energy', 'stone']],
  life: [['water', 'lightning']],
  plant: [
    ['seed', 'mud'],
    ['seed', 'earth'],
  ],
  tree: [
    ['plant', 'plant'],
    ['seed', 'water'],
  ],
  flower: [['bee', 'plant']],
  bird: [['air', 'animal']],
  egg: [
    ['bird', 'bird'],
    ['chicken', 'life'],
  ],
  fish: [['animal', 'water']],
  shark: [
    ['fish', 'storm'],
    ['fish', 'sword'],
  ],
  dolphin: [['fish', 'whale']],
  dog: [['animal', 'human']],
  bread: [['wheat', 'fire']],
  pasta: [['dough', 'tool']],
  pizza: [['dough', 'tomato']],
  cake: [
    ['dough', 'sugar'],
    ['bread', 'sugar'],
  ],
  sugar: [['plant', 'fire']],
  salt: [['sun', 'water']],
  cheese: [['milk', 'time']],
  butter: [['cow', 'tool']],
  meat: [['cow', 'fire']],
  honey: [['bee', 'fruit']],
  juice: [['fruit', 'tool']],
  tea: [['grass', 'steam']],
  coffee: [['fire', 'tree']],
  beer: [['time', 'wheat']],
  wine: [['grape', 'time']],
  human: [
    ['animal', 'knowledge'],
    ['monkey', 'tool'],
  ],
  farmer: [['human', 'wheat']],
  baker: [['dough', 'human']],
  chef: [['human', 'soup']],
  doctor: [['human', 'medicine']],
  knight: [['human', 'shield']],
  king: [['castle', 'human']],
  love: [['human', 'human']],
  baby: [['love', 'love']],
  family: [
    ['house', 'love'],
    ['baby', 'baby'],
  ],
  ghost: [['fog', 'human']],
  zombie: [
    ['human', 'time'],
    ['human', 'mud'],
  ],
  vampire: [['human', 'moon']],
  house: [
    ['wall', 'wall'],
    ['wood', 'wood'],
  ],
  city: [['bridge', 'house']],
  castle: [['king', 'wall']],
  bridge: [
    ['lake', 'stone'],
    ['metal', 'river'],
  ],
  bank: [['coin', 'house']],
  door: [['key', 'wood']],
  window: [['glass', 'house']],
  tent: [['cloth', 'forest']],
  boat: [
    ['river', 'wood'],
    ['ocean', 'wood'],
  ],
  submarine: [['ship', 'fish']],
  wheel: [['stone', 'stone']],
  car: [['energy', 'wheel']],
  plane: [['bird', 'energy']],
  helicopter: [['plane', 'wheel']],
  electricity: [['lightning', 'tool']],
  lamp: [['candle', 'glass']],
  candle: [['fire', 'paper']],
  robot: [
    ['knowledge', 'metal'],
    ['human', 'metal'],
  ],
  phone: [['computer', 'human']],
  internet: [['phone', 'phone']],
  email: [['paper', 'phone']],
  game: [['ball', 'computer']],
  tv: [
    ['computer', 'glass'],
    ['glass', 'radio'],
  ],
  radio: [['electricity', 'song']],
  microscope: [['glass', 'insect']],
  clock: [['metal', 'time']],
  watch: [['clock', 'metal']],
  hourglass: [['glass', 'time']],
  compass: [['magnet', 'ocean']],
  map: [['ocean', 'paper']],
  calendar: [['day', 'paper']],
  lock: [['door', 'key']],
  mirror: [['glass', 'lake']],
  glasses: [['book', 'glass']],
  camera: [['glass', 'phone']],
  fireworks: [['rocket', 'sky']],
  book: [['human', 'paper']],
  music: [['human', 'wind']],
  song: [['bird', 'music']],
  guitar: [['song', 'wood']],
  piano: [['metal', 'wood']],
  drum: [['cow', 'music']],
  dance: [['energy', 'human']],
  party: [
    ['dance', 'dance'],
    ['champagne', 'music'],
  ],
  movie: [
    ['camera', 'electricity'],
    ['book', 'camera'],
  ],
  painting: [['flower', 'paper']],
  money: [
    ['coin', 'paper'],
    ['coin', 'coin'],
  ],
  coin: [['gold', 'metal']],
  ball: [['air', 'cloth']],
  trophy: [['ball', 'gold']],
  medal: [['coin', 'human']],
  bed: [['cloth', 'cloud']],
  umbrella: [['cloth', 'rain']],
  shirt: [['cloth', 'cloth']],
  shoe: [['cloth', 'cow']],
  flag: [['cloth', 'wind']],
  dragon: [
    ['dinosaur', 'fire'],
    ['fire', 'snake'],
  ],
  phoenix: [['bird', 'sun']],
  unicorn: [['horse', 'magic']],
  angel: [
    ['cloud', 'human'],
    ['human', 'sky'],
  ],
  magic: [
    ['book', 'star'],
    ['energy', 'rainbow'],
  ],
  wizard: [
    ['human', 'wand'],
    ['human', 'potion'],
  ],
  fairy: [
    ['butterfly', 'magic'],
    ['butterfly', 'human'],
  ],
}

export const ELEMENTS: AlchemyElement[] = BASE_ELEMENTS.map((e) => {
  const extra = ALTERNATIVE_RECIPES[e.id]
  return extra ? { ...e, recipes: [...(e.recipes ?? []), ...extra] } : e
})

export const ELEMENT_MAP: ReadonlyMap<ElementId, AlchemyElement> = new Map(ELEMENTS.map((e) => [e.id, e]))

export const BASE_IDS: ElementId[] = ELEMENTS.filter((e) => !e.recipes).map((e) => e.id)
